### ISSUE TITLE
Drop jQuery dependency

### ISSUE THREAD

**Issue by bookercodes** [alexbooker/compareTo#1]
jQuery is not really needed in this case, I don't think. Having to reference it can be an inconvenience and so, I want to drop jQuery in favour of "vanilla JavaScript".

**Comment by GarysCorner** [comment]
Removed jQuery and enhanced support for multiple compare_To elements.  You may want to remove the "compares passwords" from the readme file since it should actually be capable of comparing almost any text based field.

happy coding,
Gary

**Comment by bookercodes** [comment]
Awesome, @GarysCorner - I'll check out your pull request now.

**Comment by bookercodes** [comment]
Regarding the "password" terminology: Even though you can compare any text-based field, the validation messages will always read "passwords do not match".

It would be quite nice if users could change the error messages, any thoughts on how to do this in an idiomatic way?

**Comment by GarysCorner** [comment]
Good point I didn't think about that.  You could probably leave the message as a default and then overwrite it using an attribute.  So maybe compareToValidTxt="Something".  And then use the hasAttribute to determine if we should overwrite the default.  But make sure you pass the default to the function generate for the onchange event, otherwise you will probably just wind up with all compareTo fields using the validation text from the last element added.  If you want me to add that in I could probably hack something together pretty quick.

**Comment by bookercodes** [comment]
I dunno... Can you name a use-case for the `compareTo` attribute **besides** passwords? 

No matter what, I think allowing people to set a  custom error is for passwords is favourable and so, I opened an issue  [here](https://github.com/alexbooker/compareTo/issues/3). 

If you want to have a stab at this then be my guest :smile:.

**Comment by GarysCorner** [comment]
I might do that, just kind of roaming around sharpening my teeth on random code.  The only other use scenario I can think of is email address verification.

**Comment by bookercodes** [comment]
Yeah, I guess so. Like I say, we can extend that option to people and they can use it however they want :smile:.
